apiVersion: v1
kind: Pod
metadata:
  name: centos-server
  annotations:
    k8s.v1.cni.cncf.io/networks: server-bridge
spec:
  containers:
  - name: centos-server
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: severalnines/centos-ssh
    securityContext:
      privileged: true
      runAsUser: 0

